### ISSUE TITLE
Movies not playing when enabled

### ISSUE THREAD

**Issue by lewri** [flathub/com.corsixth.corsixth#25]
Reported at CorsixTH/CorsixTH#2361 and some users on Discord.

Not sure where the isolation point is but the issue isn't affecting our own releases.

As we are due to launch v0.67 in the next month or so not sure if it may be worth looking into.

**Comment by rmnvgr** [comment]
After a bit of investigation, it appears during the build process, CorsixTH is linked against the FFmpeg libraries from the runtime (that don't have the necessary codecs) instead of the bundled ones.

I have planned changes to the manifest for the 0.67 release, it should fix it.

**Comment by lewri** [comment]
Do you want me to close our CorsixTH ticket now? I assume this has been implemented now for your 0.67 PR?

**Comment by rmnvgr** [comment]
Yes, you can close the CorsixTH ticket as this is purely a packaging issue. And indeed it will be fixed with the 0.67 release.
